export const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_BASE_URL ?? 'https://kopbnkasso.runasp.net/restapi/v1.0';

export const API_ENDPOINTS = {
  auth: {
    login: 'Auth/Login',
    refresh: 'Auth/Refresh',
    signup: 'Auth/Signup',
    sendOtp: 'Auth/SendOtp',
    verifyOtp: 'Auth/VerifyOtp',
    verifyForgotPasswordOtp: 'Auth/VerifyForgotPasswordOtp',
    forgotPassword: 'Auth/ForgotPassword',
    resetPassword: 'Auth/ResetPassword',
  },
  account: {
    me: 'Account/Me',
    changePassword: 'Account/ChangePassword',
    logout: 'Account/Logout',
  },
  bank: {
    create: 'Bank/Create',
    update: 'Bank/Update',
    delete: (bankId: number) => `Bank/ToggleActive?bankId=${bankId}`,
    getAll: 'Bank/GetAll',
    getById: (bankId: number) => `Bank/GetbyId/${bankId}`,
    getDropdown: 'Bank/GetDrowpdown',
    toggleActive: (bankId: number) => `Bank/ToggleActive/${bankId}`,
  },
  vacancy: {
    create: 'vacancy/create',
    getAll: 'vacancy/getall',
    update: 'Vacancy/Update',
    delete: (vacancyId: number) => `Vacancy/ToggleActive?vacancyId=${vacancyId}`,
    publish: 'Vacancy/Publish',
    uploadNoticePdf: 'Vacancy/UploadNoticePdf',
    getPublicList: 'Vacancy/GetPublicList',
    getEligibilityCriteria: (vacancyId: number) => `Vacancy/GetEligibilityCriteria?vacancyId=${vacancyId}`,
  },
  master: {
    getAllMasters: 'Master/GetAllMasters',
    getCategories: 'Master/GetCategories',
    getReligions: 'Master/GetReligions',
    getCastes: 'Master/GetCastes',
    getSubCastes: 'Master/GetSubCastes',
    getNationalities: 'Master/GetNationalities',
    getCountries: 'Master/GetCountries',
    getStates: 'Master/GetStates',
    getDistricts: 'Master/GetDistricts',
    getTalukas: 'Master/GetTalukas',
  },
  category: {
    create: 'Category/Create',
    update: 'Category/Update',
    delete: (id: number) => `Category/Delete/${id}`,
    getAll: 'Category/GetAll',
    getById: (id: number) => `Category/GetById/${id}`,
    getDropdown: 'Category/Dropdown',
    toggleActive: (id: number) => `Category/Toggle/${id}`,
  },
  author: {
    create: 'Author/Create',
    update: 'Author/Update',
    delete: (id: number) => `Author/Delete/${id}`,
    getAll: 'Author/GetAll',
    getById: (id: number) => `Author/GetById/${id}`,
    getDropdown: 'Author/Dropdown',
    toggleActive: (id: number) => `Author/Toggle/${id}`,
  },
  news: {
    create: 'news/create',
    getAll: 'news/GetAll',
    update: 'news/update',
    delete: (newsId: number) => `news/Delete/${newsId}`,
    getPublic: 'news/GetPublic',
  },
  application: {
    step1and2: 'Application/SaveStep1',
    step3: 'Application/SaveStep2',
    stepExperience: 'Application/SaveStep3',
    startOrResume: 'Application/StartOrResume',
    myApplications: 'Application/MyApplications',
    getResumeData: '/Application/GetResumeData',
    uploadDocument: '/Application/UploadDocument',
  },
  payment: {
    initiateApplication: 'Payment/InitiateApplication',
    initiateBook: 'Payment/InitiateBook',
    status: 'Payment/Status',
    receipt: 'Payment/GetReceipt',
  },
  library: {
    getMyLibrary: 'Library/GetMyLibrary',
  },
  book: {
    create: 'Book/Create',
    update: 'Book/Update',
    delete: (bookId: number) => `Book/Delete/${bookId}`,
    getAll: 'Book/GetAll',
    toggleActive: (bookId: number) => `Book/Toggle?id=${bookId}`,
  },
} as const;
